### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by s1gnature** [inu-appcenter/Uniletter_iOS#24]
## Pods
`Pods` 같은 폴더는 gitignore을 통해 관리해서 같이 안 올라가도록 하는게 좋아보여요!
용량도 용량이지만 `Podfile.lock`, `Podfile`을 통해서 버전 관리 하면서 각자 `pod install`로 버전을 맞추는게 좋습니다.
[gitignore](https://www.toptal.com/developers/gitignore) 이전에 유용하게 썼던 사이트인데 `.gitignore` 파일을 자동으로 생성해줘요
저는 보통 macOS, swift, cocoapod 세가지 추가해서 썼습니다.
참고로 SPM 같은거나 다른 옵션들 추가했을 때 `*.xcodeproj`, `*.xcworkspace` 도 포함되어 있는 경우가 많은데 이럴 경우에는 다른 사람이 프로젝트를 못 열어보니까 꼭 주의하세요!  

## 🚨 Server Address
base URL 같은 경우 또한 따로 파일을 분리해서 gitignore에 추가해서 같이 안 올라오도록 관리하는게 좋겠죠?
보안상의 문제도 있고 노출될 경우 과금 폭탄 맞을수도 있어요. 

## 접근제한자
Swift의 접근제한자에 대해서도 한번 알아보길 추천드려요!
많은 접근 제한자가 있겠지만 `private`을 적극적으로 활용하면서 다른 곳에서 쓰이지 않는 프로퍼티 or 메소드들을 숨겨보세요.
또한 `class`의 경우에 더이상의 상속이 없는 경우에는 `final` 을 활용해보세요! 이를 활용하면 다양한 이점이 있는데 한번 찾아보는걸 추천드려요!
[final 참고 블로그](https://itllbegone.tistory.com/10)

**Comment by s1gnature** [comment]
확인하셨다면 이슈 닫아주시면 됩니다~~

**Comment by vhzkclq0705** [comment]
> 확인하셨다면 이슈 닫아주시면 됩니다~~

헉 감사합니다!!!!

**Comment by leemhyungyu** [comment]
피드백 감사합니다!!
